### ISSUE TITLE
How refresh the current page

### ISSUE THREAD

**Issue by lucnap** [begriffs/angular-paginate-anything#12]
How can refresh the current page data?

**Comment by walletzilla** [comment]
I checked out latest version of js. But I setting $scope.reloadPage = true in controller does not effects data in collection. 
Here is code sample

```javascript
$scope.delete = function(id){
        $http({
            method: 'DELETE',
            url: $scope.data_url(id)
        }).success(function (data) {
            $scope.reloadPage = true;
        });
}
```

**Comment by ludmanp** [comment]
I checked out latest version of js. But I setting $scope.reloadPage = true in controller does not effects data in collection. 
Here is code sample

```javascript
$scope.delete = function(id){
        $http({
            method: 'DELETE',
            url: $scope.data_url(id)
        }).success(function (data) {
            $scope.reloadPage = true;
        });
}
```

**Comment by lucnap** [comment]
are you sure that $http().success() is executed?
make a try only next simple code with and tell me if it works
$scope.delete = function(id) {
 $scope.reloadPage = true;
}

**Comment by ludmanp** [comment]
Yes, I traced. Looks like bgfPagination decorator's $scope.reloadPage lives isolated from page controller's $scope.reloadPage.
