### ISSUE TITLE
Avoiding coupling to the REST url

### ISSUE THREAD

**Issue by stephaneeybert** [begriffs/angular-paginate-anything#42]
It would be nice to avoid coupling between the REST URL, which in some cases is referenced in a service, and not in the controller, and the directive. The directive could then be fed with the results of the REST request. Also, trying not to use the url attribute results in a cryptic $http error instead of a user friendly message.

**Comment by begriffs** [comment]
Pull requests are welcome (and I mean that in a non-jerky way; I'm happy to review changes if you send some code).
