### ISSUE TITLE
Request:  Emit pagination:resetContent when status === 205

### ISSUE THREAD

**Issue by bithive** [begriffs/angular-paginate-anything#47]
I was going to send a (tiny) pull request for this but I wasn't sure how to add a test or whether it makes sense to do more than emit something -- I just added an extra check for "reset content" status into my development copy of paginate-anything because sometimes the result set goes away and I want to be able to react to that condition (in my case by reloading the page).

> 205 Reset Content
> The server has fulfilled the request and the user agent SHOULD reset the document view which caused the request to be sent.

**Comment by begriffs** [comment]
Are you still interested in sending a pull request for this, or should I close the issue? I think it would be pretty cool functionality if you're willing to write it.

**Comment by bithive** [comment]
I'd like to do it but probably won't have time anytime soon.  You can close the issue for now.
