### ISSUE TITLE
Loading flag

### ISSUE THREAD

**Issue by ghost** [begriffs/angular-paginate-anything#49]
I use bgf-pagination directive to get a users list data from a server. I want to show a loading icon when the page loads or reloads. I tried to find a parameter in the directive to drive this loading icon and the only one I found is "reload-page" but it doesn't work. Is there any flag to do that in the current directive?

**Comment by begriffs** [comment]
I think the loading event should suffice for your problem, but we can reopen this issue if not.

**Comment by dnauck** [comment]
Easiest way to do so is to use the [angular-loading-bar](https://github.com/chieffancypants/angular-loading-bar). It works great with this directive.
