### ISSUE TITLE
Pass in a collection from resolved data

### ISSUE THREAD

**Issue by mattymess** [begriffs/angular-paginate-anything#50]
I'm resolving some data in my route and I'd like to pass it to the directive's collection instead of the directive making a second request when the view is loaded. Is this possible?

**Comment by begriffs** [comment]
Sorry, I lost track of this issue. Have you found a way around the problem in the meantime?

**Comment by mattymess** [comment]
I wasn't able to spend too much more time to figure out a way around the issue, so I just let the directive handle querying the collection. If I have some bandwidth to experiment and find a viable solution, I'll definitely let you know.
