### ISSUE TITLE
Demo does not seem to be working

### ISSUE THREAD

**Issue by panozzaj** [begriffs/angular-paginate-anything#52]
When I hit [the demo link in the README](http://begriffs.com/angular-paginate-anything/?page=0&perPage=5), I get taken to a page that just says: "Waiting for Heroku server http://pagination.begriffs.com to wake up..." Alas, it is very sleepy, and never seems to wake up. Not a huge deal, but thought I would let you know in case it was an easy fix. Thanks for the plugin!

**Comment by umdstu** [comment]
FYI you should update the 'DEMO' link in the README file since thats what people click on. Also, using this new link above, the demo doesn't work. None of the css/js assets can be found (404) either.

**Comment by begriffs** [comment]
Hm, just tried it and it works OK for me. Are you perhaps using https? I don't think the example page works with https.

**Comment by umdstu** [comment]
No, I wasn't using HTTPS. Works for me here at home though, just not at
work. Peculiar.
