### ISSUE TITLE
Problematic template url

### ISSUE THREAD

**Issue by dnauck** [begriffs/angular-paginate-anything#54]
The default template location ```tpl/paginate-anything.html``` is problematic if you install this component via bower or in a subfolder in your project.

You have to put the template manually into ```<project root>/tpl/```or change the url in the source and minified source or on every directive. I've a lot of directives in my app ;)

Does something speak against to put the template into the same location as the js files or just to embed the default template into the minified source?

If not i can prepare a pull request, but wanted to discuss first.

**Comment by begriffs** [comment]
Oh, yeah feel free to move the template and send a pull request. There's no real reason for it to be in `tpl` that I remember. Maybe I copied something I'd seen in another angular directive.

**Comment by dnauck** [comment]
See Pull Request #55

**Comment by demisx** [comment]
+1

**Comment by begriffs** [comment]
Fixed.
