### ISSUE TITLE
Range-Unit meaning

### ISSUE THREAD

**Issue by demisx** [begriffs/angular-paginate-anything#56]
Hi. What is the meaning and possible values for the `Range-Unit` header in the request and response objects? I haven't found any explanation in the README. Thank you.

**Comment by begriffs** [comment]
This directive uses the unit `items`. Traditionally http ranges were specified in `bytes` but [RFC2616 Section 3.12, custom range units](http://www.ietf.org/rfc/rfc2616.txt) allows other values. There's actually a link to this document at the bottom of the readme too, but I guess it's not very noticeable.

**Comment by demisx** [comment]
Thank you. Yeah, I missed that.
