### ISSUE TITLE
Conditional $watch:perPage

### ISSUE THREAD

**Issue by demisx** [begriffs/angular-paginate-anything#57]
Is there a need for the `perPage` watch https://github.com/begriffs/angular-paginate-anything/blob/master/src/paginate-anything.js#L200 if I don't use the perPage dropdown in the template? If not, maybe this watch could be conditional?

**Comment by begriffs** [comment]
If you have removed the dropdown then I'm guessing the watch isn't needed. My only fear would be if it somehow gets triggered on component initialization or something and sets things up. You could try removing the watch and running the tests and seeing which fail to get an idea what it affects.

Are you thinking the watch could be a drag on performance in some situations?

**Comment by demisx** [comment]
Thank you for your prompt replies. Yes, I usually don't set up a watch unless it's needed. Not a big deal when there is just one watch in question, but they do add up easily on larger projects and performance starts to drag. I've disabled it and everything works fine as far as I can tell. Some tests do fail, the ones that are coupled with this particular watch.

**Comment by demisx** [comment]
On a second thought, I think would be more efficient if attributes prefixed with "::" were treated as one-time bound attrs and weren't added to watch. Similar, to how Angular does this.

**Comment by dnauck** [comment]
The one-way binding is only available from version 1.3.x on, afaik. 

I think it's good to support angular 1.2.x for a while.
