### ISSUE TITLE
Prevent page reset to 1

### ISSUE THREAD

**Issue by demisx** [begriffs/angular-paginate-anything#58]
I've noticed that when I am viewing paginated results, let's say page 4, then click on any of the links to view the detail and then click on the browser `Back` button, the page is reset to 1. Is there a way to keep it on the same page (i.e. page 4 in this scenario)? Thank you.

**Comment by begriffs** [comment]
Your controller needs to keep track of the current page selection. For best results connect it with the url history. There's an example of this in the [sample app](http://begriffs.github.io/angular-paginate-anything),  you can read the source to see how it works.

Just to verify, I tried changing pages in the demo, navigating to a new page, then pressing back and it worked for me.

**Comment by demisx** [comment]
Thank you. I'll dig deeper into it. Just wanted to make sure I am not reinventing the wheel.
