### ISSUE TITLE
Paginate RFC-5988?

### ISSUE THREAD

**Issue by mbrooks** [begriffs/angular-paginate-anything#61]
Any plans to support pagination for RFC-5988?

We're using the api-pagination gem for rails and would like to find some support for it in angular:
https://github.com/davidcelis/api-pagination

It puts the pagination links in the headers like so:
Link: <http://localhost:3000/movies?page=1>; rel="first",
  <http://localhost:3000/movies?page=173>; rel="last",
  <http://localhost:3000/movies?page=6>; rel="next",
  <http://localhost:3000/movies?page=4>; rel="prev"

Also, RFC-5988 is the pagination method that github uses in their API:
https://developer.github.com/guides/traversing-with-pagination/

If you would like support RFC-5988, I can try my best swing at it, just point me in the right direction.

**Comment by begriffs** [comment]
Thinking about it one way, range headers are strictly more expressive than pagination link headers (I wrote about it [here](http://begriffs.com/posts/2014-03-06-beyond-http-header-links.html)). But like you say many existing servers have already implemented rfc5988. Is your motivation that you want to paginate resources sent from a server you don't control and which uses the link style pagination?

**Comment by begriffs** [comment]
I'm closing this issue. If you care to reopen let me know.
