### ISSUE TITLE
Passive copy of paginator doesn't show up

### ISSUE THREAD

**Issue by sbleon** [begriffs/angular-paginate-anything#63]
http://plnkr.co/edit/007mVhenNIdjAftfMW6K?p=preview

If you take out `passive="true"` it shows up correctly.

**Comment by begriffs** [comment]
Hmm, that's a regression. Thanks for reporting it. I'll investigate in the next few days.

**Comment by sbleon** [comment]
Thanks, @begriffs !

**Comment by sbleon** [comment]
The regression arose in 2.5.4, which included some small changes to how passive was handled:
https://github.com/begriffs/angular-paginate-anything/compare/v2.5.3...v2.5.4

**Comment by sbleon** [comment]
If I take out the `passive === 'true'` that was added in b1e04e0, my passive copies show up again.

**Comment by begriffs** [comment]
I think the passive change was made to prevent a problem with too eagerly loading something the first time around. I don't remember the details now -- @mekosan can you help remind me what the problem was?

There's a test for it in 187944b5e14d0e42e44b6487aeb12ade1a622824 but looking at it I can't see what it was all about anymore.

**Comment by sbleon** [comment]
The comment on the commit says "use of passive option on a single control".
That sounds like an unusual use case to me, and maybe not the intended
usage of `passive`.

**Comment by mekosan** [comment]
That was a while ago, but it think it was to prevent the initial load. I think I was wanting to control the first time the the plugin fired as I was getting multiple requests on the initial page load as some filters were being set.

**Comment by mihneasim** [comment]
Hello and thanks for the great work! I tried this in my first meanjs project, looking for the old mirror and the new `passive`, second pagination doesn't show up if passive, and not in sync with first, if i remove it - https://github.com/mihneasim/journeh/commit/6892852a5d62b45bcc7adb926423c4508b7ee1b1 
Dunno if helps, or just duplicating initial report.

**Comment by sbleon** [comment]
@mekosan it sounds like an additional attribute might suit your use case better. Maybe something like `ready` that would prevent any loading of items until it was true.

@begriffs I think the change from b1e04e0 is causing problems for a couple people. I suggest reverting it.

**Comment by begriffs** [comment]
I reverted the change and brought passive paginators back in new version `4.0.2`

**Comment by sbleon** [comment]
Thanks, @begriffs!

**Comment by bithive** [comment]
Now `requestRange` is getting called twice the first time the page is loaded, even though the lower paginator is defined with `passive="true"`.  Restoring the `if($scope.passive === 'true') { return; }` before the first call to `requestRange` prevents the double load, but then the passive paginator never renders the numbered page links.

**Comment by bithive** [comment]
I'm going to live with the fact that two requests fire when the page is first loaded because caching is working and it's a minor problem in the grand scheme of things.  Subsequent clicks to either paginator do behave as expected.  Thanks for continuing to maintain this directive @begriffs.
