### ISSUE TITLE
Collection Modification on pagination:loadPage

### ISSUE THREAD

**Issue by bjubinville** [begriffs/angular-paginate-anything#64]
Hello,

I've been through the issues here and came across #19 which had a couple comments about collection modification.  As @dnauck mentioned, sometimes there are instances where UI related components require some data manipulation prior to display.

A simple use case I've come up against recently is the requirement to calculate a duration based on a start and end time.  I achieve this currently by calling out to a method on a per record basis, but it would be nice to iterate over the collection after it was loaded and extending my object with my "duration" property.

I know you mentioned the possibility of adding a "transformResponse" parameter at the bottom of #19.

Any further thoughts here?  Thank you.

**Comment by begriffs** [comment]
Oh yeah I had forgotten about this issue and adding a `transformResponse` param is the way to go. I'm pretty busy with some other projects right now, can you help me with this one and send a pull request? It actually shouldn't be too hard. You can copy how `urlParams` works.

* Declare the new directive param similar to how it is done with `urlParams`: https://github.com/begriffs/angular-paginate-anything/blob/master/src/paginate-anything.js#L40
* Include it in the $http call similar to https://github.com/begriffs/angular-paginate-anything/blob/master/src/paginate-anything.js#L40
* Think about how the pagination should update itself if the param is changed, similar to https://github.com/begriffs/angular-paginate-anything/blob/master/src/paginate-anything.js#L238-L248

**Comment by bjubinville** [comment]
@begriffs sure thing.
