### ISSUE TITLE
Use ControllerAs syntax without $scope

### ISSUE THREAD

**Issue by tafs7** [begriffs/angular-paginate-anything#65]
Is it possible to configure and use this directive without depending on $scope in my controllers, since I am using ControllerAs syntax?

I'm reviewing code one of my colleagues wrote to get this wired up to a ui-grid and also provide sorting (all paging and sorting done on server side).  Here's what we have:

Controller:
```javascript
function SubjectAreaListController($scope) {
    var vm = this;
    vm.page = 0;
    vm.perPage = 2;
    vm.clientLimit = 100;
    vm.sortParams = {};
    vm.gridOptions = {};
    vm.gridOptions.useExternalSorting = true;
    vm.gridOptions.columnDefs = [
            {field: "name", displayName: "Name", cellTemplate: "<a href='#/subjectArea/edit/{{row.entity.id}}'>{{row.entity.name}}</a>"},
            {field: "owners", displayName: "Owners"}
        ];
    vm.gridOptions.onRegisterApi = onRegisterApi;

    function onRegisterApi( gridApiIn ) {
        vm.gridApiCore = gridApiIn.core;

        vm.gridApiCore.on.sortChanged($scope, onSortChanged);

        function onSortChanged(grid, sortColumns) {
            if( sortColumns.length > 1) {
                sortColumns[0].unsort(); // only sort on one column at a time
            } else if (sortColumns.length === 1) {
                vm.sortParams = { sortCol: sortColumns[0].name, sortDir: sortColumns[0].sort.direction };
            }
        }
    }
}
```

Template:
```html
<bgf-pagination
    page="vm.page"
    per-page="vm.perPage"
    client-limit="vm.clientLimit"
    url="'/api/subjectarea'"
    url-params="vm.sortParams"
    link-group-size="2"
    collection="vm.gridOptions.data"
    template-url="paginate-anything-template.html">
</bgf-pagination>

<div ui-grid="vm.gridOptions" class="grid" ui-grid-auto-resize></div>
```

**Comment by begriffs** [comment]
I'm not familiar with `ControllerAs` but I'm happy to review proposed code changes. Want to send a pull request with your idea? (Sorry for this short reply, I'm kind of overwhelmed with other projects right now but I do want to work with you to make the directive more convenient)

**Comment by tafs7** [comment]
Thanks for the reply. I will see if i can prototype something.

The main issue is in my code above around the following line:
`vm.gridApiCore.on.sortChanged($scope, onSortChanged);`

I tried replacing `$scope` with `this`, `vm`, but it didn't like either.

controllerAs was added in v1.2, and allows you to define your controller like this:

In View:
```html
<div ng-controller="MainController as vm">
    {{ vm.title }}
    {{ vm.anotherTitle }}
</div>
```

In Routes:
```javascript
$routeProvider.when("/", { 
    templateUrl: "main.html", 
    controllerAs: "vm", 
    controller: "MainController"
});
```
Then in your controller, you don't have to inject $scope, and instead use it like a normal javascript class constructor:
```javascript
app.controller("MainController", function(){
    this.title = "Some title";

    //capture the current scope in a local var to be very explicit when dealing w/ closures, etc.
    var vm = this;
    vm.anotherTitle = "another title";
});
```

**Comment by begriffs** [comment]
Pull requests are welcome. Until then I'm going to close this issue.
