### ISSUE TITLE
Navigation buttons are clickable even disabled

### ISSUE THREAD

**Issue by talski** [begriffs/angular-paginate-anything#67]
Previous and next buttons are clickable even theres no more page to go, resulting in a incorrect navigation, eg. if you click back on the first page, the current page becomes -1

**Comment by begriffs** [comment]
Oh that's bad, thanks for reporting. Looks like I broke this in version 2.1.1. The `gotoPage` function used to have a guard in it of

```javascript
if(i < 0 || i*$scope.perPage >= $scope.numItems) {
  return;
}
```

I wonder if you can help me out -- I'm kind of busy on another project right now, could you add this code, write a test and send a pull request?

**Comment by talski** [comment]
It works, sorry, tests are not for me, but thank you
