### ISSUE TITLE
Content-Range response header should include unit name according to HTTP spec but directive won't work with it

### ISSUE THREAD

**Issue by tafs7** [begriffs/angular-paginate-anything#68]
According to RFC2616 Range Headers (http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.16), the Content-Range header should include the range unit at the start of the value:

` Content-Range: items 21010-47021/47022`

My .NET/IIS server is using Web API (not ServiceStack), and I leverage a built-in class to generate the content-range header (System.Net.Http.Headers.ContentRangeHeaderValue, https://msdn.microsoft.com/en-us/library/system.net.http.headers.contentrangeheadervalue.aspx).

When I make calls to the api and use the above class, it yields the correct headers according to the spec.  However, when I look at your examples, and look at the server response you're using, the Content-Range header does not seem to include the range unit, just the from-to/total values.  This is what your server is responding with:

` Content-Range: 0-4/235886`

The directive code that parses the header using a regex (if I remember correctly from the src) is breaking for me as it expects no range unit at the beginning of that header value.  Is there something I am missing, or could this be a bug on the directive's expectations?

Here's the C# code snippet that I am using to set the appropriate headers in the response from my web api, where the from/to/count variables are set elsewhere in the code:

```csharp
response.Headers.Add("Accept-Ranges", "items");
response.Headers.Add("Range-Unit", "items");
if (_totalCount > 0)
    response.Content.Headers.ContentRange =  new ContentRangeHeaderValue(_requestedFrom, _requestedTo, _totalCount) {Unit = "items"};
```

**Comment by dnauck** [comment]
A little bit off-topic: but could you please add your WebAPI example to this wiki like the ServiceStack example?

**Comment by tafs7** [comment]
@dnauck absolutely....will be adding that later this evening

**Comment by tafs7** [comment]
@dnauck just added the WebAPI example to the wiki.  My pull request updates the README with a link to it.
