### ISSUE TITLE
Error in document with Regard to Content-Range

### ISSUE THREAD

**Issue by martijnblankestijn** [begriffs/angular-paginate-anything#80]
The documentation states that the Content-Range should look like:
"Content-Range: items 0-24/100"

I got the sample working with "Content-Range:0-1/26", indicating that the 'items' word should not be in the Content-Range header?

Is this correct?

Tested with version 4.0.2 and Angular 1.4.6

**Comment by begriffs** [comment]
Yes you are absolutely right. The word items can appear in the `Range-Unit` header but should not appear in `Content-Range`. I'll update the readme, thanks for pointing this out.
