### ISSUE TITLE
Template url attribute in documentation

### ISSUE THREAD

**Issue by martijnblankestijn** [begriffs/angular-paginate-anything#81]
The documentation states that "and provide your own template with the *templateUrl* attribute." and "and set the *template-url* attribute." somewhat further on.

There is an inconsistency between them, and the first one does not work.

Tested with version 4.0.2 of the directive, Angular 1.4.6 and Chrome 45.0.2454.101 (64-bit)

**Comment by begriffs** [comment]
You're right, good catch! I'll fix that.
