### ISSUE TITLE
UrlParams breaks PerPage

### ISSUE THREAD

**Issue by antonio-piha** [begriffs/angular-paginate-anything#84]
When $scope.urlParams is set through controller then the $scope.perPage ends undefined, or if perPage was not set at initialization.
Try line 279 in your code (watching for reloadPage) then "from" and "to" in range get value od Nan ( = 0 * undefined)

**Comment by begriffs** [comment]
Thanks for the bug report. Can you explain how it breaks? Is it possible to add a failing test case for me to see?

**Comment by antonio-piha** [comment]
I tryed to reproduce that situation on your demo on my local machine but couldn't get it. The setup was exactly the same like in my code, but the range was in correct state. I used latest version.
