### ISSUE TITLE
Stylable per-page dropdown/select template

### ISSUE THREAD

**Issue by umdstu** [begriffs/angular-paginate-anything#88]
Your default template uses a plain old select dropdown for the per-page selection. I'm working on using, as a start, angular-ui's bootstrap dropdown button. Any advice on connecting models and clicks to influence the pagination directives scoped variables?

**Comment by begriffs** [comment]
You could try attaching a modified template to the directive. The default template is https://github.com/begriffs/angular-paginate-anything/blob/master/src/paginate-anything.html

Try copying the template to a new name, modifying it, and setting the directive's `templateUrl` attribute to point at the file.

The way it works right now is that by default it uses `src/paginate-anything.html` - https://github.com/begriffs/angular-paginate-anything/blob/master/dist/paginate-anything-tpls.js#L66-L68
And `dist/angular-paginate-anything-tpls.js` bundles html into this default template - https://github.com/begriffs/angular-paginate-anything/blob/master/dist/paginate-anything-tpls.js#L357-L364

But if you override `templateUrl` then it will use your own html template wherein you're free write custom angular code for a new dropdown etc.

**Comment by umdstu** [comment]
Hey, thanks for the quick response. I apologize for not being clearer. I have already created a local template and the directive is successfully using it. My question was really directed towards how to get my dropdown button to use/modify the directive scopes values (perPage).

If I replace the select, for example, with a simple <button ng-click="updatePP(100)">. Where would this function belong? In the directive params I set perPage attribute to a scoped variable in my controller. That works. but I can't seem to update that from within the template, ie. updatePP().

Does that make more sense?

**Comment by begriffs** [comment]
I think you're right that you have to create a function in your controller $scope for an ng-click, as demonstrated here http://www.infragistics.com/community/blogs/dhananjay_kumar/archive/2015/06/29/how-to-work-with-the-bootstrap-dropdown-in-angularjs.aspx

Does your example work if you put `pp` in your controller rather than in the template code? Perhaps in the template you could then say `<button ng-click="$parent.pp(100)">`

**Comment by umdstu** [comment]
I'll keep working on it, thanks.
