### ISSUE TITLE
Live Demo

### ISSUE THREAD

**Issue by prasad47** [begriffs/angular-paginate-anything#90]
Is there any live demo link with markup,javascript ?

**Comment by dnauck** [comment]
The is one big and fat DEMO link in the first paragraph of the readme.

**Comment by prasad47** [comment]
Is there any live demo link "with markup,javascript " ?

**Comment by dnauck** [comment]
It is with markup and JS .. just look at the page code or in the gh-pages branch. Its a single index.html with everything inline.

**Comment by begriffs** [comment]
Just a note the demo does not work right under https because it requests http on the backend and that mismatch causes a security problem. Attempting to use https on the backend does not work because the cert is not valid when applied as a subdomain of begriffs.com (it's a heroku cert).

**Comment by prasad47** [comment]
ok Mr..Begriffs I Understood https part . Thanks
