### ISSUE TITLE
Demo on heroku doesn't load because of protocol conflict

### ISSUE THREAD

**Issue by Thatkookooguy** [begriffs/angular-paginate-anything#94]
Heroku demos load on `https`, but you included `http://pagination.begriffs.com/words` with `http`.

In order to support both http and https, include everything like so: `//pagination.begriffs.com/words`. Removing the protocol allows the web page to use the same protocol the site uses

**Comment by Thatkookooguy** [comment]
![capture](https://cloud.githubusercontent.com/assets/10427304/15057123/e7083414-131d-11e6-83a3-4b6692b87387.PNG)

**Comment by begriffs** [comment]
Thanks for pointing this out. I may also have to reference the underlying Heroku hostname rather than pagination.begriffs.com so that the SSL certificate matches.

**Comment by begriffs** [comment]
@Thatkookooguy I fixed the demo page, thanks again for pointing out the problem.

**Comment by Thatkookooguy** [comment]
ofc :-) thanks for the quick fix!
