### ISSUE TITLE
Per Page Presets change after changing page size

### ISSUE THREAD

**Issue by umdstu** [begriffs/angular-paginate-anything#96]
So when the pagination starts off, my preset per-page options are [10,25,50,100,250]. If I select 250 from the dropdown, 250 (im assuming, never counted) results show up. The per-page dropdown then gets set to 100 and the list is updated to have the options [10,25,50,100]. 250 is no longer an option, even if you set it back to 10 per page. In my offline usage, i am seeing 267 pages @ 10 per page (by default), so I know I have 250+ results. Any idea why this would be happening?

**Comment by begriffs** [comment]
Weird, thanks for reporting. I'm not able to reproduce using the demo at http://begriffs.github.io/angular-paginate-anything/ what version of the library are you using?

**Comment by umdstu** [comment]
Happy to help. I'll look into it further today and get you the version
number.

**Comment by umdstu** [comment]
Ok, no error here. As I dug through to find the problem, it was traced back
to my server side, where I essentially implemented my own version of your
clean-pagination gem. I had a MAX_PAGE_SIZE set to 100. Seems to be ok
after setting that.

Sorry for the false report, clearly the javascript is behaving as expected
:)

**Comment by begriffs** [comment]
OK, glad you figured it out.
